# docker-compose setup for local development & testing
version: '3.4'

services:
  junction:
    build:
      context: .
      args:
        PROJECT_NAME: junction
        PROJECT_VERSION: 0.0.1-test
    depends_on:
      - "pebble"
    environment:
      - SECRET_KEY=secret
      - ACME_URL=acme://pebble/pebble
      - DATASTORE=tmp/data
      - CERT_PASSWORD=password
      - ADMIN_TOKEN=token
      - EMAIL_ADDRESS=test@mail.com
      - HTTP_PORT=5002
      - HTTPS_PORT=8443
      - BIND_ADDRESS=0.0.0.0
    ports:
      - "8000:8000"
      - "5002:5002"
      - "8443:8443"
  pebble:
    image: letsencrypt/pebble
    command: pebble
    expose:
      - 14000
    ports:
      - "14000:14000"  # ACME port
      - "15000:15000"  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
  pebble-novalidate: # use novalidate for acceptance tests to avoid doing full host mapping
    image: letsencrypt/pebble
    command: pebble
    ports:
      - "14000:14000"  # ACME port
    environment:
      - PEBBLE_VA_NOSLEEP=1
      - PEBBLE_VA_ALWAYS_VALID=1
  integration-test:
    build:
      context: ./
      dockerfile: ./src/integrationTest/resources/Dockerfile
    volumes:
      - ./build/reports/tests:/app/build/reports/tests
    depends_on:
      - "junction"
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1460

