# docker-compose setup for local development & testing
version: '3.4'

services:
  junction:
    build:
      context: .
      args:
        PROJECT_NAME: junction
        PROJECT_VERSION: 0.0.1-test
    depends_on:
      - "pebble"
    environment:
      - SECRET_KEY=secret
      - ACME_URL=acme://pebble
  pebble:
    image: letsencrypt/pebble
    command: pebble
    expose:
      - 14000
    ports:
      - "14000:14000"  # ACME port
      - "15000:15000"  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
    extra_hosts:
      - "server1:host-gateway"
      - "server2:host-gateway"
  test-curl:
    image: curlimages/curl
    command: curl -iv https://closetbrewingproject.co.uk/api/routes
    extra_hosts:
      - "closetbrewingproject.co.uk:host-gateway"
  integration-test:
    build:
      context: src/integrationTest/resources
    extra_hosts:
      - "server1:host-gateway"
      - "server2:host-gateway"
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1460

